//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace technologyWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int addressID { get; set; }
        public int usID { get; set; }
        public string city { get; set; }
        public string discrict { get; set; }
        public string neighbourhood { get; set; }
        public string street { get; set; }
        public string fullAddress { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
