//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace technologyWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int detailsID { get; set; }
        public int orID { get; set; }
        public int productID { get; set; }
        public int pieces { get; set; }
        public decimal totalPrice { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
