//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace technologyWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payID { get; set; }
        public int orID { get; set; }
        public string payMethod { get; set; }
        public string payStatus { get; set; }
        public byte[] createdDate { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
